### ISSUE TITLE
テレフォン機能

### ISSUE THREAD

**Issue by Naoya-Tagawa** [Umadachi564/advanced_team_work#1]
GPTのAPIでそれっぽいことをする？

**Comment by saikiRA1011** [comment]
Open AI公式
https://openai.com/blog/openai-api

Open AI APIで提供されているモデルの説明
https://openai.itshinan.jp/models/

gpt-3.5-turboを使うのがコスト的にもよさそう

**Comment by Umadachi564** [comment]
実装完了
